name: Create Packages and Release.gpg

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Install build requirements
        run: sudo apt install zstd bzip2 xz-utils
        
      - 
        name: Build repo
        run: |
          bash repo.sh
      -
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
    name: artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: /Packages /Packages.xz /Packages.bz2 /Packages.zst /Release
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail
    
    - name: Deploy GitHub Pages site
  uses: actions/deploy-pages@v1.2.3
  with:
    emit_telemetry: false
    conclusion: # optional
    # GitHub token
    token: ${{ github.token }}
    timeout: 600000
    error_count: 10
    reporting_interval: 5000
    artifact_name: # optional, default is github-pages
    
