name: Create Packages and Release.gpg

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Install build requirements
        run: sudo apt install zstd bzip2 xz-utils
        
      - 
        name: Build repo
        run: |
          bash repo.sh
      -
        name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
         # Artifact name
         name: github-pages
         # Path of the directory containing the static assets.
         path: /home/runner/work/m00nl1ghts.github.io/m00nl1ghts.github.io
      -
        name: Deploy 
        uses: actions/deploy-pages@v1.2.3
        with:
          emit_telemetry: false
        # GitHub token
          token: ${{ secrets.TOKEN_GITHUB }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
    
