on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron: "*/595 * * * *" # every 9 hours & 55 minutes
    
name: Stash Commits
jobs:
  make:
    name: Stash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
          
      - name: Run git stash
        run: |
          git stash

      - name: Commit To Repo
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: 'Add Automated Update'
          signoff: true
